MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

LTO_ENABLE = yes
OLED_ENABLE = yes
COMBO_ENABLE = yes

# Enable WPM feature
WPM_ENABLE = yes

# Enable RGB Matrix
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

CONVERT_TO=rp2040_ce
